name: Trigger ruyi-package-ci on tag

on:
  push:
    tags:
      - '*'

jobs:
  dispatch-ruyi-package-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ruyi-package-ci
        env:
          GH_TOKEN: ${{ secrets.RUYI_PACKAGE_CI_TOKEN }}
          TARGET_REPO: ruyisdk/ruyi-package-ci
          TARGET_REF: master
          WORKFLOW: deb.yml
          RUYI_DEB_REF: ${{ github.ref_name }}
        run: |
          if [ -z "${GH_TOKEN:-}" ]; then
            echo "GH_TOKEN empty. Secret not set or not exposed to this job."
            exit -1
          fi

          curl -L -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            https://api.github.com/repos/${TARGET_REPO}/actions/workflows/${WORKFLOW}/dispatches \
            -d '{ "ref": "'${TARGET_REF}'", "inputs": { "ruyi_deb_ref": "'${RUYI_DEB_REF}'" } }'
